# Generated by Django 5.2.6 on 2025-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Недвижимость')),
                ('last_name', models.CharField(max_length=150, verbose_name='Вид недвижимости')),
                ('year', models.CharField(choices=[('first', 'Первичная недвижимость'), ('second', 'Новостройки'), ('third', 'Дома со сроком эксплуатации до X лет'), ('fourth', 'Старый жилой фонд')], default='first', max_length=6, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'квартира',
                'verbose_name_plural': 'квартиры',
                'ordering': ['last_name'],
            },
        ),
    ]
