# Generated by Django 6.0a1 on 2025-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                    ("unpublished", "Снято с публикации"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
