# Generated by Django 5.2.6 on 2025-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Вид недвижимости'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='last_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Площадь (кв.м)'),
        ),
    ]
