# Generated by Django 5.2.6 on 2025-10-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория Недвижимости",
                "verbose_name_plural": "Категории Недвижимости",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "verbose_name": "Объект Недвижимости",
                "verbose_name_plural": "Объекты Недвижимости",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание категории",
                max_length=200,
                null=True,
                verbose_name="Описание категории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите категорию",
                max_length=150,
                verbose_name="Категория Недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Введите дату создания объекта недвижимости",
                null=True,
                verbose_name="Дата создания объекта недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание объекта недвижимости",
                max_length=300,
                null=True,
                verbose_name="Описание объекта недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото объекта недвижимости",
                null=True,
                upload_to="photos/",
                verbose_name="Фото объекта недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите наименование объекта недвижимости",
                max_length=150,
                verbose_name="Наименование объекта недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Введите цену объекта недвижимости",
                max_digits=10,
                verbose_name="Цена объекта недвижимости",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Введите дату последнего изменения объекта недвижимости",
                null=True,
                verbose_name="Дата последнего изменения объекта недвижимости",
            ),
        ),
    ]
