# Generated by Django 5.2.6 on 2025-10-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_catalog_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['last_name'], 'verbose_name': 'Объект недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
    ]
