# Generated by Django 5.2.6 on 2025-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='year',
            field=models.CharField(choices=[('Первичная недвижимость', 'Первичная недвижимость'), ('Новостройки', 'Новостройки'), ('Дома со сроком эксплуатации до X лет', 'Дома со сроком эксплуатации до X лет'), ('Старый жилой фонд', 'Старый жилой фонд')], default='Первичная недвижимость', max_length=66, verbose_name='Состояние объекта'),
        ),
    ]
