# Generated by Django 5.2.6 on 2025-10-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_product_delete_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория Недвижимости', 'verbose_name_plural': 'Категории Недвижимости'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Категория Недвижимости'),
        ),
    ]
